[package]
name = "lice"
description = "Little Intermediate Combinator Expressions"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { version = "1.0" }
parse-display = { version = "0.8.2" }
nom = { version = "7.1.3", default-features = false, features = [ "alloc" ] }
petgraph = { version = "0.6.4" }
lice-macros = { path = "../lice-macros" }
log = { version = "0.4.20" }
