[package]
name = "lice"
description = "Little Intermediate Combinator Expressions"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = [ "graph" ]
std = []
file = [ "std", "dep:nom" ]
graph = [ "file", "dep:petgraph" ]

[dependencies]
lice-macros = { path = "../lice-macros" }
anyhow = { version = "1.0" }
log = { version = "0.4" }
parse-display = { version = "0.9" }
nom = { version = "7.1", default-features = false, features = [ "alloc" ], optional = true }
petgraph = { version = "0.6", optional = true }
