#!/usr/bin/env bash
# Convenience wrapper script for running gmhs, i.e., `git mhs`

root="$(git rev-parse --show-toplevel)"

# Ensure mhs is built
git submodule update --init
make -C "$root/MicroHs" --quiet bin/gmhs

# Note that without an explicit -o flag, mhs will write to out.comb
"$root/MicroHs/bin/gmhs" "-i$root/MicroHs/lib" "$@"
